// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/monzo/terrors/proto/error.proto

package terrorsproto

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StackFrame struct {
	Filename             string   `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Line                 int32    `protobuf:"varint,2,opt,name=line,proto3" json:"line,omitempty"`
	Method               string   `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StackFrame) Reset()         { *m = StackFrame{} }
func (m *StackFrame) String() string { return proto.CompactTextString(m) }
func (*StackFrame) ProtoMessage()    {}
func (*StackFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae33a222c066248f, []int{0}
}

func (m *StackFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StackFrame.Unmarshal(m, b)
}
func (m *StackFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StackFrame.Marshal(b, m, deterministic)
}
func (m *StackFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StackFrame.Merge(m, src)
}
func (m *StackFrame) XXX_Size() int {
	return xxx_messageInfo_StackFrame.Size(m)
}
func (m *StackFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_StackFrame.DiscardUnknown(m)
}

var xxx_messageInfo_StackFrame proto.InternalMessageInfo

func (m *StackFrame) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *StackFrame) GetLine() int32 {
	if m != nil {
		return m.Line
	}
	return 0
}

func (m *StackFrame) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

type Error struct {
	Code                 string              `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string              `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Params               map[string]string   `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Stack                []*StackFrame       `protobuf:"bytes,4,rep,name=stack,proto3" json:"stack,omitempty"`
	Retryable            *wrappers.BoolValue `protobuf:"bytes,5,opt,name=retryable,proto3" json:"retryable,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae33a222c066248f, []int{1}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetParams() map[string]string {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *Error) GetStack() []*StackFrame {
	if m != nil {
		return m.Stack
	}
	return nil
}

func (m *Error) GetRetryable() *wrappers.BoolValue {
	if m != nil {
		return m.Retryable
	}
	return nil
}

func init() {
	proto.RegisterType((*StackFrame)(nil), "StackFrame")
	proto.RegisterType((*Error)(nil), "Error")
	proto.RegisterMapType((map[string]string)(nil), "Error.ParamsEntry")
}

func init() {
	proto.RegisterFile("github.com/monzo/terrors/proto/error.proto", fileDescriptor_ae33a222c066248f)
}

var fileDescriptor_ae33a222c066248f = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x51, 0x31, 0x4f, 0xf3, 0x30,
	0x10, 0x55, 0x9a, 0xa6, 0xdf, 0xd7, 0x0b, 0x42, 0xc8, 0x42, 0xc8, 0xca, 0x80, 0x42, 0xa7, 0xa8,
	0x83, 0x23, 0x95, 0xa5, 0x30, 0x56, 0x2a, 0x33, 0x0a, 0x88, 0x81, 0xcd, 0x6d, 0xaf, 0x69, 0xd5,
	0x38, 0x17, 0xd9, 0x2e, 0xa8, 0xfc, 0x73, 0x36, 0x14, 0x3b, 0xa1, 0x4c, 0x79, 0x2f, 0xf7, 0xee,
	0xdd, 0xbd, 0x33, 0x4c, 0xcb, 0xbd, 0xdd, 0x1d, 0x57, 0x62, 0x4d, 0x2a, 0x57, 0x54, 0x7f, 0x51,
	0x6e, 0x51, 0x6b, 0xd2, 0x26, 0x6f, 0x34, 0x59, 0xca, 0x1d, 0x11, 0x0e, 0x27, 0xb7, 0x25, 0x51,
	0x59, 0xa1, 0xaf, 0xac, 0x8e, 0xdb, 0xfc, 0x53, 0xcb, 0xa6, 0x41, 0x6d, 0x7c, 0x7d, 0xf2, 0x0a,
	0xf0, 0x62, 0xe5, 0xfa, 0xf0, 0xa4, 0xa5, 0x42, 0x96, 0xc0, 0xff, 0xed, 0xbe, 0xc2, 0x5a, 0x2a,
	0xe4, 0x41, 0x1a, 0x64, 0xe3, 0xe2, 0x97, 0x33, 0x06, 0xc3, 0x6a, 0x5f, 0x23, 0x1f, 0xa4, 0x41,
	0x16, 0x15, 0x0e, 0xb3, 0x1b, 0x18, 0x29, 0xb4, 0x3b, 0xda, 0xf0, 0xd0, 0xa9, 0x3b, 0x36, 0xf9,
	0x0e, 0x20, 0x5a, 0xb6, 0x5b, 0xb4, 0x5d, 0x6b, 0xda, 0xf4, 0x6e, 0x0e, 0x33, 0x0e, 0xff, 0x14,
	0x1a, 0x23, 0x4b, 0x6f, 0x36, 0x2e, 0x7a, 0xca, 0xa6, 0x30, 0x6a, 0xa4, 0x96, 0xca, 0xf0, 0x30,
	0x0d, 0xb3, 0x78, 0xc6, 0x84, 0x73, 0x11, 0xcf, 0xee, 0xe7, 0xb2, 0xb6, 0xfa, 0x54, 0x74, 0x0a,
	0x76, 0x07, 0x91, 0x69, 0x37, 0xe7, 0x43, 0x27, 0x8d, 0xc5, 0x39, 0x47, 0xe1, 0x2b, 0x6c, 0x0e,
	0x63, 0x8d, 0x56, 0x9f, 0xe4, 0xaa, 0x42, 0x1e, 0xa5, 0x41, 0x16, 0xcf, 0x12, 0xe1, 0x0f, 0x22,
	0xfa, 0x83, 0x88, 0x05, 0x51, 0xf5, 0x26, 0xab, 0x23, 0x16, 0x67, 0x71, 0xf2, 0x00, 0xf1, 0x9f,
	0x99, 0xec, 0x0a, 0xc2, 0x03, 0x9e, 0xba, 0x10, 0x2d, 0x64, 0xd7, 0x10, 0x7d, 0xb4, 0x4d, 0x5d,
	0x02, 0x4f, 0x1e, 0x07, 0xf3, 0x60, 0x71, 0xf9, 0x7e, 0xd1, 0x3d, 0x87, 0x1f, 0x31, 0x72, 0x9f,
	0xfb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x73, 0x23, 0x7c, 0x40, 0xb6, 0x01, 0x00, 0x00,
}
