// Code generated by protoc-gen-go. DO NOT EDIT.
// source: error.proto

package terrorsproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StackFrame struct {
	Filename             string   `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Line                 int32    `protobuf:"varint,2,opt,name=line,proto3" json:"line,omitempty"`
	Method               string   `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StackFrame) Reset()         { *m = StackFrame{} }
func (m *StackFrame) String() string { return proto.CompactTextString(m) }
func (*StackFrame) ProtoMessage()    {}
func (*StackFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_0579b252106fcf4a, []int{0}
}

func (m *StackFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StackFrame.Unmarshal(m, b)
}
func (m *StackFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StackFrame.Marshal(b, m, deterministic)
}
func (m *StackFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StackFrame.Merge(m, src)
}
func (m *StackFrame) XXX_Size() int {
	return xxx_messageInfo_StackFrame.Size(m)
}
func (m *StackFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_StackFrame.DiscardUnknown(m)
}

var xxx_messageInfo_StackFrame proto.InternalMessageInfo

func (m *StackFrame) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *StackFrame) GetLine() int32 {
	if m != nil {
		return m.Line
	}
	return 0
}

func (m *StackFrame) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

type Error struct {
	Code    string            `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Params  map[string]string `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Stack   []*StackFrame     `protobuf:"bytes,4,rep,name=stack,proto3" json:"stack,omitempty"`
	// We don't use google.protobuf.BoolValue as it doesn't serialize properly without jsonpb.
	Retryable            *BoolValue `protobuf:"bytes,5,opt,name=retryable,proto3" json:"retryable,omitempty"`
	MarshalCount         int32      `protobuf:"varint,6,opt,name=marshal_count,json=marshalCount,proto3" json:"marshal_count,omitempty"`
	MessageChain         []string   `protobuf:"bytes,7,rep,name=message_chain,json=messageChain,proto3" json:"message_chain,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_0579b252106fcf4a, []int{1}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetParams() map[string]string {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *Error) GetStack() []*StackFrame {
	if m != nil {
		return m.Stack
	}
	return nil
}

func (m *Error) GetRetryable() *BoolValue {
	if m != nil {
		return m.Retryable
	}
	return nil
}

func (m *Error) GetMarshalCount() int32 {
	if m != nil {
		return m.MarshalCount
	}
	return 0
}

func (m *Error) GetMessageChain() []string {
	if m != nil {
		return m.MessageChain
	}
	return nil
}

type BoolValue struct {
	Value                bool     `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoolValue) Reset()         { *m = BoolValue{} }
func (m *BoolValue) String() string { return proto.CompactTextString(m) }
func (*BoolValue) ProtoMessage()    {}
func (*BoolValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_0579b252106fcf4a, []int{2}
}

func (m *BoolValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoolValue.Unmarshal(m, b)
}
func (m *BoolValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoolValue.Marshal(b, m, deterministic)
}
func (m *BoolValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoolValue.Merge(m, src)
}
func (m *BoolValue) XXX_Size() int {
	return xxx_messageInfo_BoolValue.Size(m)
}
func (m *BoolValue) XXX_DiscardUnknown() {
	xxx_messageInfo_BoolValue.DiscardUnknown(m)
}

var xxx_messageInfo_BoolValue proto.InternalMessageInfo

func (m *BoolValue) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

func init() {
	proto.RegisterType((*StackFrame)(nil), "StackFrame")
	proto.RegisterType((*Error)(nil), "Error")
	proto.RegisterMapType((map[string]string)(nil), "Error.ParamsEntry")
	proto.RegisterType((*BoolValue)(nil), "BoolValue")
}

func init() { proto.RegisterFile("error.proto", fileDescriptor_0579b252106fcf4a) }

var fileDescriptor_0579b252106fcf4a = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x51, 0x31, 0x6f, 0xf2, 0x30,
	0x10, 0x55, 0x08, 0x09, 0xe4, 0xc2, 0xf7, 0xa9, 0x3a, 0x55, 0x95, 0xc5, 0x14, 0xe8, 0x12, 0x75,
	0xc8, 0x40, 0x97, 0xb6, 0x23, 0x88, 0xce, 0x95, 0x5b, 0x75, 0xe8, 0x82, 0x4c, 0x70, 0x0b, 0xc2,
	0x8e, 0x91, 0x6d, 0x2a, 0xf1, 0xbb, 0xfa, 0x07, 0x2b, 0x3b, 0x86, 0x74, 0xf2, 0xbd, 0xe7, 0x77,
	0x77, 0xef, 0xe9, 0x20, 0xe7, 0x5a, 0x2b, 0x5d, 0x1d, 0xb4, 0xb2, 0x6a, 0xfa, 0x06, 0xf0, 0x6a,
	0x59, 0xbd, 0x7f, 0xd6, 0x4c, 0x72, 0x1c, 0xc3, 0xf0, 0x73, 0x27, 0x78, 0xc3, 0x24, 0x27, 0x51,
	0x11, 0x95, 0x19, 0xbd, 0x60, 0x44, 0xe8, 0x8b, 0x5d, 0xc3, 0x49, 0xaf, 0x88, 0xca, 0x84, 0xfa,
	0x1a, 0x6f, 0x20, 0x95, 0xdc, 0x6e, 0xd5, 0x86, 0xc4, 0x5e, 0x1d, 0xd0, 0xf4, 0xa7, 0x07, 0xc9,
	0xd2, 0x6d, 0x71, 0x5d, 0xb5, 0xda, 0x9c, 0xa7, 0xf9, 0x1a, 0x09, 0x0c, 0x24, 0x37, 0x86, 0x7d,
	0xb5, 0xc3, 0x32, 0x7a, 0x86, 0x78, 0x07, 0xe9, 0x81, 0x69, 0x26, 0x0d, 0x89, 0x8b, 0xb8, 0xcc,
	0x67, 0x58, 0xf9, 0x29, 0xd5, 0x8b, 0x27, 0x97, 0x8d, 0xd5, 0x27, 0x1a, 0x14, 0x38, 0x81, 0xc4,
	0x38, 0xe7, 0xa4, 0xef, 0xa5, 0x79, 0xd5, 0xe5, 0xa0, 0xed, 0x0f, 0x96, 0x90, 0x69, 0x6e, 0xf5,
	0x89, 0xad, 0x05, 0x27, 0x49, 0x11, 0x95, 0xf9, 0x0c, 0xaa, 0xb9, 0x52, 0xe2, 0x9d, 0x89, 0x23,
	0xa7, 0xdd, 0x27, 0xde, 0xc2, 0x3f, 0xc9, 0xb4, 0xd9, 0x32, 0xb1, 0xaa, 0xd5, 0xb1, 0xb1, 0x24,
	0xf5, 0x29, 0x47, 0x81, 0x5c, 0x38, 0xce, 0x8b, 0x5a, 0xa3, 0xab, 0x7a, 0xcb, 0x76, 0x0d, 0x19,
	0x14, 0x71, 0x99, 0xd1, 0x51, 0x20, 0x17, 0x8e, 0x1b, 0x3f, 0x42, 0xfe, 0xc7, 0x2d, 0x5e, 0x41,
	0xbc, 0xe7, 0xa7, 0x10, 0xdf, 0x95, 0x78, 0x0d, 0xc9, 0xb7, 0x5b, 0x1f, 0xb2, 0xb7, 0xe0, 0xa9,
	0xf7, 0x10, 0x4d, 0x27, 0x90, 0x5d, 0xcc, 0x75, 0x32, 0xd7, 0x3a, 0x0c, 0xb2, 0xf9, 0xff, 0x8f,
	0x91, 0xf5, 0xe7, 0x33, 0xfe, 0x7c, 0xeb, 0xd4, 0x3f, 0xf7, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x1e, 0xff, 0x45, 0x11, 0xd4, 0x01, 0x00, 0x00,
}
